### ISSUE TITLE
✨ Custom URLs

### ISSUE THREAD

**Issue by axlon** [LaraCrafts/laravel-url-shortener#23]
Suggested [here](https://www.reddit.com/r/laravel/comments/bgv5ro/we_have_created_an_url_shortener_package/elnyvz1?utm_source=share&utm_medium=web2x), it would be nice to be able to create a custom short URL for drivers that support it.

A new interface should be added to supported drivers that allows for the following functionality:

```
$driver->shortenTo(string $url, string $identifier, array $options = [])
$driver->shortenToAsync(string $url, string $identifier, array $options = [])
```

**Comment by yak0d3** [comment]
Adding a new interface, IMO, would be the best way to handle this, having something like `CreatesCustomUrls`  interface would help us (and the other devs) differ between the drivers that support Custom URLs and the ones that does not. 
I don't have any specific ideas, but i am sure using a new interface would also make other things easier in the future.

**Comment by nerg4l** [comment]
Example from the Laravel library: 

- Cache::tags (https://laravel.com/docs/5.8/cache#cache-tags)
  - Method does not exists on objects where it is not implemented
  - `BadMethodCallException` is executed by `\Illuminate\Cache\Repository::tags` method 
  - No interface for enforcing method
  - Alert added in documentation
- Database::dropColumn (https://laravel.com/docs/5.8/migrations#dropping-columns)
  - Commands are validated
  - `BadMethodCallException` is executed by `\Illuminate\Database\Schema\Blueprint::ensureCommandsAreValid` method
  - Alert added in documentation

**Comment by yak0d3** [comment]
@nerg4l  Using interfaces (and _abstracts_) makes the code more flexible, for instance, there might be a use case where the developer needs to inject drivers that only support Custom URLs, in such a case _type hinting_ the parameter would get the job done, while throwing an _Exception_ will only make the code uglier with unnecessary `try` `catch` blocks.

As an example, the [**Symfony Cache Component**](https://symfony.com/doc/current/components/cache.html)  introduces the [`TagAwareCacheInterface`](https://github.com/symfony/symfony/blob/4.2/src/Symfony/Contracts/Cache/TagAwareCacheInterface.php) that must be implemented in drivers (so called Adapters) that allow Invalidating Cache Items by their _tags_ using the [`invalidateTags()`](https://github.com/symfony/symfony/blob/7ca637ed0e73f8d58db379c7584e35520cab2be5/src/Symfony/Contracts/Cache/TagAwareCacheInterface.php#L37) method.

We may also want to add features that are only applicable on drivers that support Custom URLs, such as allowing developers to define a specific algorithm (or format) for generating Custom URLs, in this situation we may easily do something similar to the following example:

```php
public function generateUrl(CreatesCustomUrls $driver)
{
   //Logic here...
    $driver->shortenTo($url, $identifier, $options)
}
```

**Comment by nerg4l** [comment]
@yak0d3 When I don't use `might`, `should`, `could`, `must`, `in my opinion` or similar keyword/phrase I add the comment as a documentation not as a suggestion. Just to take everything into consideration during the implementation.

**Comment by axlon** [comment]
So @yak0d3 your opinion is pretty clear I think, @nerg4l which approach do you think is best?

**Comment by nerg4l** [comment]
@axlon Having an interface is the better way. Still I'm curious why the creators of Laravel decided to do it differently.

Maybe the in between approach would be to add an interface but before calling instead of checking the interface (or after the interface check) check if the driver has the method. This way the interface is not forced but used as a "contract".

**Comment by axlon** [comment]
> Maybe the in between approach would be to add an interface but before calling instead of checking the interface (or after the interface check) check if the driver has the method. This way the interface is not forced but used as a "contract".

Which object would do the checking? The driver itself?

**Comment by nerg4l** [comment]
An `Adapter` object in-between the manager and the driver.

**Comment by yak0d3** [comment]
From my point of view, checking whether the driver implements a certain method while going with the Interface approach makes the Interface meaningless, we could just check the method existence without introducing the new Interface in this case. But.. Isn't this the main concept of Interfaces; enforcing methods so that we can use them later on?

**Comment by nerg4l** [comment]
Do what @yak0d3 proposed. Create an interface for `shortenTo` and `shortenToAsync` (I saw you already created one with `CustomUrls` name). If the driver does not implement this interface throw a `BadMethodCallException`. To make this work an `Adapter` object should be added as I stated before.

Adapter patter:

> Allows the interface of an existing class to be used as another interface.

Note:

- `\Illuminate\Notifications\Channels\BroadcastChannel::getData`
Checks if `toBroadcast` or `toArray` methods exists on the instance and throws a `RuntimeException` if not.
- `\Illuminate\Bus\Dispatcher::dispatchToQueue`
Checks if `$queue` is instance of `\Illuminate\Contracts\Queue\Queue` and throws a `RuntimeException` if not.

The difference here from the previous examples is that these are not called directly by the user and that's why they throw `RuntimeException` and not `BadMethodCallException`.
